import type { MetadataRoute } from 'next';

// Generated by app-engine: scripts/add-seo-surface.mjs
const BASE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://speak-to-me-theta.vercel.app';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: '*',
      allow: '/',
      // Private and per-user areas: no value in the index, and some leak state.
      disallow: ['/api/', '/admin/', '/dashboard/', '/account/', '/settings/', '/profile/', '/owner/', '/auth/', '/signin/', '/sign-in/', '/signup/', '/sign-up/', '/login/', '/logout/', '/onboarding/', '/checkout/', '/billing/', '/invite/', '/reset-password/', '/verify/'],
    },
    sitemap: `${BASE_URL}/sitemap.xml`,
  };
}
