import type { MetadataRoute } from 'next';

// Generated by app-engine: scripts/add-seo-surface.mjs
// Re-run that script after adding pages so search engines see them.
const BASE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://speak-to-me-theta.vercel.app';

const ROUTES: Array<{ path: string; priority: number }> = [
  { path: '/', priority: 1 },
];

export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();
  return ROUTES.map(({ path, priority }) => ({
    url: `${BASE_URL}${path === '/' ? '' : path}`,
    lastModified,
    changeFrequency: priority === 1 ? 'weekly' : 'monthly',
    priority,
  }));
}
